/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2018-03-02 01:32:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.xz.page.Main;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("  <head>\r\n");
      out.write("    <title>能耗管理平台</title>\r\n");
      out.write("    <meta http-equiv=\"content-type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("    <link rel=\"shortcut icon\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/images/Common/logo.gif\" type=\"image/x-icon\" />\r\n");
      out.write("    <script type=\"text/javascript\" src=\"../../js/Common/common.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"../../bootstrap/css/bootstrap.min.css\" >\r\n");
      out.write("  \t<script type=\"text/javascript\" src=\"../../js/Common/jquery.min.js\"></script>\r\n");
      out.write("  \t<script type=\"text/javascript\" src=\"../../bootstrap/js/bootstrap.min.js\"></script>\r\n");
      out.write("  \t<script type=\"text/javascript\" src=\"../../js/Main/init.js\"></script>\r\n");
      out.write("  </head>\r\n");
      out.write("  <style>\r\n");
      out.write("          *{\r\n");
      out.write("              margin:0;\r\n");
      out.write("              padding:0;\r\n");
      out.write("          }\r\n");
      out.write("            html,body{\r\n");
      out.write("                width:100%;\r\n");
      out.write("                height: 100%;\r\n");
      out.write("                overflow: hidden;\r\n");
      out.write("            }\r\n");
      out.write("            #headerId{\r\n");
      out.write("                width:100%;\r\n");
      out.write("                height:8%;\r\n");
      out.write("                background-color: rgb(74,164,162);\r\n");
      out.write("            }\r\n");
      out.write("          #footerId{\r\n");
      out.write("              width:100%;height:5.9%;background-color:rgb(153,153,153);\r\n");
      out.write("              position:fixed;\r\n");
      out.write("              bottom:0;\r\n");
      out.write("              left:0;\r\n");
      out.write("              font-size:16px;\r\n");
      out.write("              font-weight:bold;\r\n");
      out.write("              color:#fff;\r\n");
      out.write("              /*text-align: center;*/\r\n");
      out.write("              display:flex;\r\n");
      out.write("              justify-content: center;\r\n");
      out.write("              align-items: center;\r\n");
      out.write("          }\r\n");
      out.write("          .container{\r\n");
      out.write("              width:100%;\r\n");
      out.write("              min-height:90%;\r\n");
      out.write("              background-color:rgb(242,242,242);\r\n");
      out.write("              padding-top:1%;\r\n");
      out.write("              display: flex;\r\n");
      out.write("          }\r\n");
      out.write("          .container section{\r\n");
      out.write("              width:86.7%;\r\n");
      out.write("              margin: 0 auto;\r\n");
      out.write("              background-color:#fff;\r\n");
      out.write("              display: inline-flex;\r\n");
      out.write("              justify-content:center;\r\n");
      out.write("              align-items: center;\r\n");
      out.write("          }\r\n");
      out.write("          .container section #imgDiv{\r\n");
      out.write("              text-align: center;\r\n");
      out.write("              height:auto;\r\n");
      out.write("          }\r\n");
      out.write("          .container section #imgDiv span{\r\n");
      out.write("          \t\tfont-family:\"微软雅黑\";\r\n");
      out.write("              font-size:14px;\r\n");
      out.write("          }\r\n");
      out.write("      </style>\r\n");
      out.write("  <body>\r\n");
      out.write("  \t<div id=\"headerId\"></div>\r\n");
      out.write("\t<div class=\"container\" >\r\n");
      out.write("\t\t\t<section>\r\n");
      out.write("                <div id=\"imgDiv\">\r\n");
      out.write("                    <img src=\"../../images/Main/welcome.png\" style=\"display: block\"/>\r\n");
      out.write("                    <span>欢迎进入能耗管理平台</span>\r\n");
      out.write("                </div>\r\n");
      out.write("            </section>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"footerId\"></div>  \r\n");
      out.write("  </body>\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
